/*COMPOSITE DATA TYPE*/
/*PL/SQL RECORDS*/
DECLARE
   TYPE T_EMP IS RECORD(
       EMPID NUMBER, 
       EMPNAME EMPLOYEES.FIRST_NAME%TYPE, 
       MGRNAME EMPLOYEES.FIRST_NAME%TYPE);
   R_EMP T_EMP;
BEGIN
   SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME EMPNAME, MGR.FIRST_NAME MGRNAME
        INTO R_EMP
   FROM EMPLOYEES EMP JOIN EMPLOYEES MGR
   ON EMP.MANAGER_ID = MGR.EMPLOYEE_ID
   WHERE EMP.EMPLOYEE_ID = 101;
   DBMS_OUTPUT.PUT_LINE('Employee:' || R_EMP.EMPNAME || '(' || 
    R_EMP.EMPID || ') reporting to ' || 
    R_EMP.MGRNAME);
END;
/
DECLARE 
    V_EMP EMPLOYEES%ROWTYPE;
BEGIN
    SELECT * INTO V_EMP FROM EMPLOYEES WHERE EMPLOYEE_ID = 103;
    DBMS_OUTPUT.PUT_LINE(V_EMP.EMPLOYEE_ID || '-'|| V_EMP.FIRST_NAME || ' ' ||
        V_EMP.LAST_NAME);
END;
/
DECLARE
   TYPE T_DEP IS RECORD(
       DEPID NUMBER, 
       EMPREC EMPLOYEES%ROWTYPE);
   R_DEP T_DEP;  
   
   R_RETIREDEMP retired_emps%ROWTYPE;
   
BEGIN
    R_DEP.DEPID := 10;
    SELECT * INTO R_DEP.EMPREC FROM EMPLOYEES WHERE EMPLOYEE_ID = 103;
    DBMS_OUTPUT.PUT_LINE(R_DEP.EMPREC.EMPLOYEE_ID 
        || '-'|| R_DEP.EMPREC.FIRST_NAME || ' ' ||
        R_DEP.EMPREC.LAST_NAME || ' DepID:' || R_DEP.DEPID || 
        ' Empid:' || R_DEP.EMPREC.EMPLOYEE_ID);
        
    INSERT INTO EMPTEMP VALUES R_DEP.EMPREC;
    
    R_DEP.EMPREC.HIRE_DATE := SYSDATE;
    UPDATE EMPTEMP SET ROW = R_DEP.EMPREC WHERE EMPLOYEE_ID = R_DEP.EMPREC.EMPLOYEE_ID;    
    
    SELECT EMPLOYEE_ID EMPNO, FIRST_NAME ENAME, JOB_ID JOB
        , MANAGER_ID MGR, HIRE_dATE HIREDATE, SYSDATE LEAVEDATE, SALARY SAL, 
        COMMISSION_PCT COMM, DEPARTMENT_ID DEPTNO INTO R_RETIREDEMP
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = 105;

    INSERT INTO RETIRED_EMPS VALUES R_RETIREDEMP;
    
END;
/

SELECT * FROM RETIRED_EMPS;
TRUNCATE TABLE EMPTEMP;
DROP TABLE EMPTEMP;
create table empTemp as select * from employees where employee_id = 0;
SELECT * FROM EMPTEMP;
/*PL/SQL COLLECTIONS*/
/*ASSOCIATIVE ARRAY / INDEX BY TABLE*/
DECLARE
   TYPE EMP_TABLE_TYPE IS TABLE OF EMPLOYEES.EMAIL%TYPE
      INDEX BY PLS_INTEGER;
   EMP_TABLE EMP_TABLE_TYPE;
BEGIN
   EMP_TABLE(100) := 'SKING';
   EMP_TABLE(105) := 'DAUSTIN';
   EMP_TABLE(110) := 'JCHEN';
   DBMS_OUTPUT.PUT_LINE(EMP_TABLE(100));
   DBMS_OUTPUT.PUT_LINE(EMP_TABLE(105));
   DBMS_OUTPUT.PUT_LINE(EMP_TABLE(110)); 
   EMP_TABLE('1') := 'TESTCHAR';
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE(1)); 
END;
/
DECLARE
    TYPE EMP_TABLE_TYPE IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY VARCHAR2(20);
    EMP_TABLE EMP_TABLE_TYPE;
BEGIN
    SELECT * INTO EMP_TABLE('ONE') FROM EMPLOYEES WHERE EMPLOYEE_ID = 105;
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE('ONE').EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE('ONE').FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE('ONE').LAST_NAME); 
    DBMS_OUTPUT.PUT_LINE('---');
    SELECT * INTO EMP_TABLE(2) FROM EMPLOYEES WHERE EMPLOYEE_ID = 106;
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE(2).EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE(2).FIRST_NAME);
    DBMS_OUTPUT.PUT_LINE(EMP_TABLE(2).LAST_NAME);
END;
/
DECLARE
   TYPE emp_table_type IS TABLE OF
      employees%ROWTYPE INDEX BY PLS_INTEGER;
   my_emp_table  emp_table_type;
   max_count         NUMBER(3):= 104; 
BEGIN
  FOR i IN 100..max_count
  LOOP
   SELECT * INTO my_emp_table(i) FROM employees
   WHERE employee_id = i;
  END LOOP;
  FOR i IN my_emp_table.FIRST..my_emp_table.LAST 
  LOOP
     DBMS_OUTPUT.PUT_LINE(my_emp_table(i).last_name);
  END LOOP;
END; 
/

DECLARE
    TYPE EMP_TABLE_TYPE IS TABLE OF EMPLOYEES%ROWTYPE INDEX BY VARCHAR2(20);
    EMP_TABLE EMP_TABLE_TYPE;
    L_INDEX VARCHAR2(20);
BEGIN
    SELECT * INTO EMP_TABLE('ONE') FROM EMPLOYEES WHERE EMPLOYEE_ID = 105;
    
    SELECT * INTO EMP_TABLE(2) FROM EMPLOYEES WHERE EMPLOYEE_ID = 106;
    
    L_INDEX := EMP_TABLE.FIRST();
    WHILE (L_INDEX IS NOT NULL) LOOP
        DBMS_OUTPUT.PUT_LINE('key:' || l_index || '/value:' || EMP_TABLE(L_INDEX).LAST_NAME);        
        L_INDEX := EMP_TABLE.NEXT(L_INDEX);        
    END LOOP;    
END;
/
/*PL/SQL COLLECTIONS*/
/*NESTED TABLE*/
DECLARE
 TYPE dept_mail IS TABLE OF VARCHAR2(20);
 mails dept_mail := dept_mail('SKING', 'NKOCHAR', 'LDEHAAN', 'AHUNOLD');
BEGIN
 FOR i IN mails.FIRST..mails.LAST LOOP
   DBMS_OUTPUT.PUT_LINE(mails(i));
 END LOOP;
 DBMS_OUTPUT.PUT_LINE('----');
 mails := dept_mail('KING', 'NKOCHAR', 'LDEHAAN', 'AHUNOLD','RGORES','THERESA');
  FOR i IN mails.FIRST..mails.LAST LOOP
   DBMS_OUTPUT.PUT_LINE(mails(i));
 END LOOP;
END;
/
/*PL/SQL COLLECTIONS*/
/*VARRAY*/
DECLARE
 TYPE emp_mail IS VARRAY(5) OF VARCHAR2(20);
 mails emp_mail := emp_mail('NKOCHAR', 'LDEHAAN', 'AHUNOLD','SKING','JCHEN');
BEGIN
 FOR i IN mails.FIRST..mails.LAST LOOP
   DBMS_OUTPUT.PUT_LINE(mails(i));
 END LOOP;
 mails := emp_mail('RGORES','THERESA');
  FOR i IN mails.FIRST..mails.LAST LOOP
   DBMS_OUTPUT.PUT_LINE(mails(i));
 END LOOP;
END;
/
create table retired_emps
(empno number(4), ename varchar2(10),job varchar2(9),
mgr number(4), hiredate date, leavedate date, sal number(7,2), comm number (7,2),
deptno number(2));